spring.application.name=odontoflow-backend

# DataSource
spring.datasource.url=jdbc:postgresql://localhost:5433/odontoflow
spring.datasource.username=postgres
spring.datasource.password=788606
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# API
server.servlet.context-path=/api

# Springdoc / Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method

# JWT
jwt.secret=kiiAJlI51lYiRN1bKhFTlHDYq7Igw8AWoTSh9lx09tx
jwt.expiration=86400000

# Object storage (MinIO / S3) — Pre-Signed URLs
storage.endpoint=http://localhost:9000
storage.region=us-east-1
storage.access-key=admin
storage.secret-key=supersecretpassword
storage.bucket=odontoflow
storage.presign-minutes=15
