-- Hibernate Envers audit trail (NFR01)

CREATE TABLE revinfo
(
    rev      INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    revtstmp BIGINT,
    user_id  VARCHAR(255),
    CONSTRAINT pk_revinfo PRIMARY KEY (rev)
);

CREATE TABLE patients_aud
(
    id             UUID     NOT NULL,
    rev            INTEGER  NOT NULL,
    revtype        SMALLINT,
    tenant_id      UUID,
    full_name      VARCHAR(255),
    date_of_birth  DATE,
    medical_alerts TEXT,
    created_at     TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_patients_aud PRIMARY KEY (id, rev),
    CONSTRAINT fk_patients_aud_rev FOREIGN KEY (rev) REFERENCES revinfo (rev)
);

CREATE TABLE clinical_records_aud
(
    id                 UUID    NOT NULL,
    rev                INTEGER NOT NULL,
    revtype            SMALLINT,
    tenant_id          UUID,
    patient_id         UUID,
    appointment_id     UUID,
    odontogram_data    JSONB,
    clinical_notes     TEXT,
    created_by_user_id UUID,
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_clinical_records_aud PRIMARY KEY (id, rev),
    CONSTRAINT fk_clinical_records_aud_rev FOREIGN KEY (rev) REFERENCES revinfo (rev)
);
